services:
  backend:
    build:
      context: ./backend
    container_name: operation-guide-backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/operationguide
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: operation-guide-frontend
    ports:
      - "3000:80"  # NGINX in production container listens on 80
    depends_on:
      - backend

  db:
    image: postgres:14
    container_name: operation-guide-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: operationguide
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

volumes:
  postgres_data: