services:
  - type: web
    name: operation-guide-backend
    env: python
    buildCommand: ""
    startCommand: gunicorn backend.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: DATABASE_URL
        fromDatabase:
          name: operation-guide-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: .onrender.com
    autoDeploy: true
    plan: free

databases:
  - name: operation-guide-db
