# Generated by Django 5.1.7 on 2025-03-27 22:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Назва може містити лише літери, цифри, пробіли та дефіси.', regex='^[\\w\\s\\-]+$')]),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='text',
            field=models.TextField(validators=[django.core.validators.RegexValidator(message='Відгук має бути не менше 10 символів.', regex='^.{10,}$')]),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='title',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Заголовок має бути не коротший 5 символів.', regex='^.{5,}$')]),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='views',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='step',
            name='order',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Імʼя має бути не менше 2 символів.', regex='^.{2,}$')])),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(validators=[django.core.validators.RegexValidator(message='Коментар має бути не менше 10 символів.', regex='^.{10,}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instruction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='guides.instruction')),
            ],
        ),
    ]
