# Generated by Django 5.1.7 on 2025-05-06 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0003_topic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='App',
            new_name='Program',
        ),
        migrations.RenameField(
            model_name='instruction',
            old_name='app',
            new_name='program',
        ),
        migrations.AddField(
            model_name='topic',
            name='program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='guides.program'),
            preserve_default=False,
        ),
    ]
