# Generated by Django 5.1.6 on 2025-03-05 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instruction',
            old_name='content',
            new_name='steps',
        ),
        migrations.AddField(
            model_name='instruction',
            name='category',
            field=models.CharField(choices=[('viber', 'Viber'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('settings', 'Налаштування')], default='settings', max_length=50),
        ),
        migrations.AddField(
            model_name='instruction',
            name='description',
            field=models.TextField(default='Apps'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instruction',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='instructions_images/'),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='os_type',
            field=models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], max_length=10),
        ),
    ]
